version: "3.8"

services:

  mongo:
    image: mongo:7
    container_name: product-config-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
  backend:
    build: ./backend
    container_name: product-config-backend
    ports: 
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/products
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo-data: